name: Run Test Suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Matches your environment (from your error: python3.12)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .  # Installs gaussf_pipeline package
          pip install pandas scipy numpy tqdm  # Explicitly install all required dependencies

      - name: Run kmer_freq_dist test
        run: |
          python test_data/test_kmer_freq_dist.py
          ls test_data/output/kmer_freq_dist/*_kmers.csv  # Verify output exists

      - name: Run kmer_counter test
        run: |
          python test_data/test_kmer_counter.py
          ls test_data/output/kmer_counter.csv  # Verify output exists

      - name: Run merge_normalize test
        run: |
          python test_data/test_merge_normalize.py
          ls test_data/output/*_merged_normalized.csv  # Verify output exists

      - name: Run gaussf_tpm test
        run: |
          python test_data/test_gaussf_tpm.py
          ls test_data/output/results.csv  # Verify output exists

      - name: Upload test artifacts (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test_data/output/*.csv
            test_data/output/*.log  # Include logs if your scripts generate them
