name: Gaussf Pipeline Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Adjust to your Python version (e.g., 3.9)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # Install your package in editable mode
          pip install pytest

      - name: Run tests
        run: |
          pytest test_data/ --verbose

      - name: Upload test results (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_data/

